# Generated by Django 6.0.6 on 2026-06-12 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('TUBERCULOSIS', 'Tuberculosis'), ('MALARIA', 'Malaria')], max_length=50)),
                ('model_prediction', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('result_source_flag', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=50)),
                ('image_reference', models.ImageField(blank=True, null=True, upload_to='diagnoses_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='accounts.patientprofile')),
            ],
        ),
    ]
