# Generated by Django 6.0.6 on 2026-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='note_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='ROUTINE', max_length=50),
        ),
    ]
