# Generated by Django 6.0.6 on 2026-06-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_allergies_patientprofile_blood_group_and_more'),
        ('records', '0002_doctornote_note_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(default='MediSight Clinic', max_length=255)),
                ('vitals', models.CharField(blank=True, max_length=255, null=True)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('examination', models.TextField(blank=True, null=True)),
                ('investigations', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='accounts.doctorprofile')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='records.patientrecord')),
            ],
        ),
    ]
