# Generated by Django 6.0.6 on 2026-06-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_allergies_patientprofile_blood_group_and_more'),
        ('records', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_scans/')),
                ('result', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_scans', to='accounts.doctorprofile')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scans', to='records.patientrecord')),
            ],
        ),
    ]
